name: Playwright Tests

on:
  push:
    branches:
      - main  # Runs tests on push to 'main' branch
  pull_request:
    branches:
      - main  # Runs tests on pull request to 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the GitHub runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use Node.js version 16

    - name: Install dependencies
      run: |
        npm install  # Install all dependencies

    - name: Install Playwright and dependencies
      run: |
        npx playwright install --with-deps  # Install Playwright and required browsers

    - name: Run Playwright tests on Chromium
      run: |
        npx playwright test practiceForm.spec.js --project=chromium  # Run tests only on Chromium (Chrome)
