name: Playwright Tests

on:
  push:
    branches:
      - main  # Runs tests when you push to 'main' branch
  pull_request:
    branches:
      - main  # Runs tests on pull request to 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify Ubuntu as the runner environment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can specify the node version you want to use

    - name: Install dependencies
      run: |
        npm install  # or yarn install if you're using yarn

    - name: Install Playwright browsers
      run: |
        npx playwright install --with-deps  # Install Playwright with required dependencies

    - name: Run Playwright tests
      run: |
        npx playwright test  # Run your tests
